org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
neogradle.subsystems.parchment.minecraftVersion=1.21.1
neogradle.subsystems.parchment.mappingsVersion=2024.11.17
minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
neo_version=21.1.248
neo_version_range=[21.1.236,)
loader_version_range=[1,)
# Mod info
mod_id=more_docking_connectors
mod_name=Create: More Docking Connectors
mod_license=MIT
mod_version=2.0.0
mod_group_id=com.cake.more_docking_connectors
mod_authors=Cake
mod_description=Adds additional docking ports to Create: Simulated, allowing kinetic and improved fluid transfer between sublevels.
# Dependencies
create_version=6.0.10-280
ponder_version=1.0.82
flywheel_version=1.0.6
registrate_version=MC1.21-1.3.0+67
simulated_version=1.3.0
aeronautics_version=1.3.0
sable_version=2.0.5
veil_version=4.0.1
